language: java
jdk: oraclejdk8
install: true
before_install: 
install: mvn test
script:
  - jdk_switcher use oraclejdk8
  - mvn clean verify
  - mvn archetype:generate -DgroupId=com.mycompany.app -DartifactId=my-app -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false
cache:
  directories:
  - $HOME/.m2
notifications:
        email: false
sudo: false

