language: java
jdk: oraclejdk8
install: true
script:
  - jdk_switcher use oraclejdk8
cache:
  directories:
  - $HOME/.m2
notifications:
        email:
                on_success: always
                on_failure: never
sudo: false

